language: android

android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

branches:
  only:
    - master
    - develop

before_install:
  # for gradle output style
  - export TERM=dumb

  # environment info
  - gradle -v
  - uname -a

script:
  - ./gradlew clear makeJar assembleDefault
  - ./gradlew build -x test

notifications:
  email:
    on_success: never
    on_failure: change
