language: android

android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

branches:
  only:
    - master
    - develop

before_install:
  # for gradle output style
  - export TERM=dumb

  # environment info
  - gradle -v
  - uname -a

script:
  - ./gradlew clear makeJar assembleDefault
  - ./gradlew build -x test

notifications:
  email:
    on_success: never
    on_failure: change
