language: android

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23

branches:
  only:
    - master
    - develop

script:
  - ./gradlew clear makeJar assembleDefault
  - ./gradlew build -x test

before_install:
  - pip install --user codecov

after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: change
